=== tiendv/filnalproject/Source code/QAWeb/XMLConfig/config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio Developer Edition (Trial) 8.1.5.2538 (http://www.liquid-technologies.com)-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="table" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="table-name">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string" />
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:sequence>
                                <xs:element name="field" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="relation" minOccurs="0">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="related-table" type="xs:string" minOccurs="0" />
                                                        <xs:element name="relation-name" type="xs:string" />
                                                        <xs:element name="reversed-relation" type="xs:string" minOccurs="0" />
                                                        <xs:element name="mapping-table" type="xs:string" minOccurs="0" />
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="field-name" type="xs:string" minOccurs="0" />
                                        </xs:sequence>
                                        <xs:attribute name="type" type="xs:string" use="required" />
                                        <xs:attribute name="field-alias" type="xs:string" />
                                        <xs:attribute name="visible" type="xs:boolean" default="true" />
                                        <xs:attribute name="presentation" type="xs:boolean" default="false" />
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                            <xs:element name="primary-key" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                        <xs:attribute name="table-alias" type="xs:string" use="optional" />
                        <xs:attribute name="visible" type="xs:boolean" default="true" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="database-name" type="xs:string" />
                <xs:element name="mapping-table" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="table-key" type="xs:string" />
                            <xs:element name="related-table-key" type="xs:string" />
                            <xs:element name="mapping-table-name" type="xs:string" />
                            <xs:element name="name" type="xs:string" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tiendv/filnalproject/Source code/QAWeb/XMLConfig/rel_config.xml
<?xml version="1.0" encoding="utf-8"?>

<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/IT/Final%20Project/DatabaseQAConfig/config.xsd">
    <table table-alias="Publication"> <!-- Tên do người dùng đặt thay thế cho dblp_pub_new -->
        <table-name>dblp_pub_new</table-name>
        <field type="String" field-alias="author" visible="false" relation="related table">
            <!--Thông tin này không được hiển thị cho người dùng-->
            <relation>
                <relation-name>has author</relation-name> 
                <relation-name>has writer</relation-name>
                <relation-name>has composer</relation-name>
                <relation-name>be write</relation-name>
                <relation-name>be compose</relation-name>
                <reversed-relation>write</reversed-relation>
                <reversed-relation>compose</reversed-relation>
                <reversed-relation>has write</reversed-relation>
                <reversed-relation>has compose</reversed-relation> 
                <related-table>author</related-table>               
            </relation>
            <field-name>author</field-name>
        </field>
        
        <field type="String" field-alias="title" visible="true" relation="has attribute">
            <relation>
                <relation-name>has title</relation-name>
                <relation-name>has heading</relation-name>
            </relation>
            <field-name>title</field-name>
        </field>
        
        <field type="String" field-alias="source" visible="true" relation="has attribute">
            <relation>
                <relation-name>has source</relation-name>
                <relation-name>from</relation-name>
                <relation-name>in</relation-name>
                <relation-name>result from</relation-name>
            </relation>
            <field-name>source</field-name>
        </field>
              
        <field type="Int" field-alias="year" visible="true" relation="has attribute">
            <relation>
                <relation-name>has year</relation-name>
                <relation-name>in</relation-name>
                <relation-name>from</relation-name>
                <relation-name>to</relation-name>
            </relation>
            <field-name>year</field-name>
        </field>
        
        <field type="String" field-alias="type" visible="true" relation="has attribute">
            <relation>
                <relation-name>has type</relation-name>
            </relation>
            <field-name>type</field-name>
        </field>

        <field type="String" field-alias="isbn" visible="true" relation="has attribute">
            <relation>
                <relation-name>have</relation-name>
                <relation-name>has</relation-name>
            </relation>
            <field-name>isbn</field-name>
        </field>

        <field type="String" field-alias="doi" visible="true" relation="has attribute">
            <relation>
                <relation-name>have</relation-name>
                <relation-name>has</relation-name>
            </relation>
            <field-name>isbn</field-name>
        </field>
        
        <field type="String" field-alias="publisher" visible="true" relation="has attribute">
            <relation>
                <relation-name>has publisher</relation-name>
                <relation-name>be publish</relation-name>
                <relation-name>be release</relation-name>
                <reversed-relation>publish</reversed-relation>
                <reversed-relation>has publish</reversed-relation>
                <reversed-relation>release</reversed-relation>
                <reversed-relation>has release</reversed-relation>
            </relation>
            <field-name>publisher</field-name>
        </field>
        
        <primary-key>id</primary-key>
        
    </table>
    
    <database-name>dblp</database-name> 	
 
    <related-table>
        <name>author</name>
        <related-table-name>dblp_author_ref_new</related-table-name> 
        <table-key>pub_id</table-key>
    </related-table>
</database>

=== tiendv/filnalproject/DatabaseQAConfig/SampleFile.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio Developer Edition (Trial) 8.1.5.2538 (http://www.liquid-technologies.com) -->
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/IT/Final%20Project/DatabaseQAConfig/config.xsd">
    <table table-alias="publication"> <!-- Tên do người dùng đặt thay thế cho dblp_pub_new -->
        <table-name>dblp_pub_new</table-name>
        <field type="String" field-alias="author" visible="false">
            <!--Thông tin này không được hiển thị cho người dùng-->
            <relation>
                <relation-name>has author,be write</relation-name> <!--Thiết lập các loại quan hệ chính sẽ xuất hiện trong câu hỏi -->
                <reversed-relation>write</reversed-relation>
                <mapping-table>pub_author</mapping-table> <!-- Thông tin ánh xạ -->
            </relation>
          
        </field>
        <field type="String" field-alias="title" visible="true">
            <relation>
                <relation-name>has title</relation-name> 
                <!-- Vì thuộc tính này không được ánh xạ thông qua table nào khác nên nó sẽ không có mapping-table hoặc related-table -->
            </relation>
            <field-name>title</field-name>
        </field>
   
        
        <field type="String" field-alias="source" visible="true">
            <relation>
                <relation-name>has source</relation-name>
            </relation>
            <field-name>source</field-name>
        </field>
        
        <!-- Các thuộc tính khác -->
        <!-- ................... -->
        <!-- ................... -->
        
        <field type="Int" field-alias="year" visible="true">
            <relation>
                <relation-name>has year</relation-name>
            </relation>
            <field-name>year</field-name>
        </field>
        
        <field type="String" field-alias="type" visible="true">
            <relation>
                <relation-name>has type</relation-name>
            </relation>
            <field-name>type</field-name>
        </field>
        
        <field type="String" field-alias="publisher" visible="true">
            <relation>
                <relation-name>has publisher,be publish</relation-name>
                <reversed-relation>publish</reversed-relation>
            </relation>
            <field-name>publisher</field-name>
        </field>
        
        <primary-key>id</primary-key>
        
    </table>
    
    <database-name>dblp</database-name>
 
    <mapping-table>
        <mapping-table-name>dblp_author_ref_new</mapping-table-name> <!-- Tên table mapping là dblp_author_ref_new trong database -->
        <name>pub_author</name>
        <table-key>pub_id</table-key>
        <related-table-key>author</related-table-key>
	</mapping-table>
</database>
